

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Configuration 
    value: |
     Config1
     Config2
     Config3
     Config4
     Config5

steps:
- script: |
    python --version
  displayName: 'Check Python Version'


- script: |

      for PythonScript in {1..5}; do
        echo "Executing PythonScript_${PythonScript} in $configFolder"
        python RELEASE_CONFIGURATIONS/$configFolder/PythonScript_${PythonScript}.py
      done

- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py