

trigger:
- main 

pool:
  name: Default       
steps: 


- script: |
    workingDirectory: $(Build.SourcesDirectory)
    python run_script.py Config_1 Config_2 Config_3 Config_4 Config_5
    python RELEASE_CONFIGURATIONS/initial_file.py


 
       
 

       




