parameters:
- name: RunPythonScripts
  displayName: Run RunPythonScripts
  type: string
  values:
    - Required
    - Off
  default: Off
- name: RunConfig1
  displayName: Run RunConfig1
  type: string
  values:
    - Required
    - Off
  default: Off
- name: RunConfig2
  displayName: Run RunConfig2
  type: string
  values:
    - Required
    - Off
  default: Off
- name: RunConfig3
  displayName: Run RunConfig3
  type: string
  values:
    - Required
    - Off
  default: Off
- name: RunConfig4
  displayName: Run RunConfig4
  type: string
  values:
    - Required
    - Off
  default: Off
- name: RunConfig5
  displayName: Run RunConfig5
  type: string
  values:
    - Required
    - Off
  default: Off
 
trigger:
      - main

pool:
  name : Default

variables:
  system.debug: true

stages:
- stage: RunPythonScripts
  displayName: RunPythonScripts
  jobs:
  - job: RunPythonScripts
    pool:
      Default
    steps:
 
    # Run initial_file.py with specified arguments
    - script: |
        python RELEASE_CONFIGURATIONS/initial_file.py
        
 
    - script: |
        python RELEASE_CONFIGURATIONS/initial_file.py Config_1
      displayName: 'Execute PythonScript in Config_1'
      condition: eq('${{ parameters.RunConfig1 }}', 'Required')
 
    - script: |
        python RELEASE_CONFIGURATIONS/initial_file.py Config_2
      displayName: 'Execute PythonScript in Config_2'
      condition: eq('${{ parameters.RunConfig2 }}', 'Required')
    - script: |
        python RELEASE_CONFIGURATIONS/initial_file.py Config_3
      displayName: 'Execute PythonScript in Config_3'
      condition: eq('${{ parameters.RunConfig3 }}', 'Required')
 
    - script: |
        python RELEASE_CONFIGURATIONS/initial_file.py Config_4
      displayName: 'Execute PythonScript in Config_4'
      condition: eq('${{ parameters.RunConfig4 }}', 'Required')
 
    - script: |
        python RELEASE_CONFIGURATIONS/initial_file.py Config_5
      displayName: 'Execute PythonScript in Config_5'
      condition: eq('${{ parameters.RunConfig5 }}', 'Required')


