

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
      RELEASE_CONFIGURATIONS/Config_1/
      RELEASE_CONFIGURATIONS/Config_2/
      RELEASE_CONFIGURATIONS/Config_3/
      RELEASE_CONFIGURATIONS/Config_4/
      RELEASE_CONFIGURATIONS/Config_5/

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- script: |

    IFS=$'\n' read -rd '' -a folderPaths <<< "${{ variables.Config }}"
    for folderPath in "${folderPaths[@]}"; do
      echo "Processing folder: $folderPath"
      python "$folderPath/PythonScript1.py"  # Replace PythonScript1.py with your Python script filename
    done



- script: |
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript1_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript2_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript3_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript4_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript5_config1.py