

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
     Config1
     Config2
     Config3
     Config4
     Config5

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- script: echo "Executing script for config1"
  displayName: 
  condition: eq(variables['config'], 'config1')




