

trigger:
- main 

pool:
  name: Default 

steps:

- script: |
    python --version
  displayName: 'Check Python Version'




- script: |
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript1_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript2_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript3_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript4_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript5_config1.py