

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
     Config1
     Config2
     Config3
     Config4
     Config5

steps:
- script: |
    python --version
  displayName: 'Check Python Version'


- script: |

    if [ "${{ variables.config }}" == "$(Config1)" ]; then
      for scriptNumber in {1..5}; do
        echo "Executing PythonScript_${scriptNumber} in ${variables.config}"
        python RELEASE_CONFIGURATIONS/${variables.config}/PythonScript_${scriptNumber}.py
      done
    else
      echo "Config is not config1, skipping Python script execution."
    fi

- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py