

trigger:
- main 

pool:
  name: Default 
  workingDirectory: $(Build.SourcesDirectory) 
steps: 
- script: |
  
    python RELEASE_CONFIGURATIONS/initial_file.py > output.txt
    python RELEASE_CONFIGURATIONS/initial_file.py config_1 > Config_1.txt
    python RELEASE_CONFIGURATIONS/initial_file.py config_2 > Config_2.txt
    python RELEASE_CONFIGURATIONS/initial_file.py config_3 > Config_3.txt
    python RELEASE_CONFIGURATIONS/initial_file.py config_4 > Config_4.txt
    python RELEASE_CONFIGURATIONS/initial_file.py config_5 > Config_5.txt

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'Test'


       
 

       




