

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
      RELEASE_CONFIGURATIONS/Config_1/
      RELEASE_CONFIGURATIONS/Config_2/
      RELEASE_CONFIGURATIONS/Config_3/
      RELEASE_CONFIGURATIONS/Config_4/
      RELEASE_CONFIGURATIONS/Config_5/

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- script: |

    i=PythonScript1_config1.py
    while [ $i -le PythonScript5 ]; do  # Change 5 to the number of scripts you want to execute
      echo "Executing PythonScript_$i.py"
      python RELEASE_CONFIGURATIONS/Config_$i/PythonScript_$i.py
      i=$((i+1))
    done



- script: |
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript1_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript2_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript3_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript4_config1.py
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript5_config1.py