

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
     Config1
     Config2
     Config3
     Config4
     Config5

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      if [ "$(config)" == "Config1" ]; then
              python PythonScript1.py
              python PythonScript2.py
              python PythonScript3.py
              python PythonScript4.py
              python PythonScript5.py




- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py