

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
      RELEASE_CONFIGURATIONS/Config_1/
      RELEASE_CONFIGURATIONS/Config_2/
      RELEASE_CONFIGURATIONS/Config_3/
      RELEASE_CONFIGURATIONS/Config_4/
      RELEASE_CONFIGURATIONS/Config_5/

steps:
- script: |
    python --version
  displayName: 'Check Python Version'




- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py