

trigger:
- main 

pool:
  name: Default 
  workingDirectory: $(Build.SourcesDirectory) 
steps: 
- script: |
  
    python RELEASE_CONFIGURATIONS/initial_file.py > output.txt


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/output.txt'
    artifact: 'Test'


       
 

       




