

trigger:
- main  # Define the branch to trigger the pipeline on, e.g., 'main' or 'master'

pool:
  name: Default  # Define the VM image to use for the build environment

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you want to use, e.g., '3.x' or '3.8'
    architecture: 'x64'  # Specify the architecture of the Python version, e.g., 'x64' or 'x86'

- script: |
    python PythonScript1_config1.py  # Replace 'YourPythonScript.py' with the name of your Python script
  displayName: 'Run Python script'