

trigger:
- main 

pool:
  name: Default 
  workingDirectory: $(Build.SourcesDirectory) 
steps: 
- script: |
  
    python RELEASE_CONFIGURATIONS/initial_file.py

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/my-working-directory'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/my-artifact-folder'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/my-artifact-folder'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'Test'


       
 

       




