

trigger:
- main 

pool:
  name: Default 

steps:
- checkout: self
  path: RELEASE_CONFIGURATIONS/Config_1 # Checkout config1 directory from the repository


- script: |

    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py




       




