

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Configuration 
    value: |
     Config1
     Config2
     Config3
     Config4
     Config5

steps:
- script: |
    python --version
  displayName: 'Check Python Version'


- script: |
    IFS=$'\n' read -rd '' -a configs <<< "${Configurations}"
    for configFolder in "${configs[@]}"; do
      echo "Processing configuration folder: $configFolder"
      for scriptNumber in {1..5}; do
        echo "Executing PythonScript_${scriptNumber} in $configFolder"
        python RELEASE_CONFIGURATIONS/$configFolder/PythonScript_${scriptNumber}.py
      done
    done

- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py