

trigger:
- main 

pool:
  name: Default 
  workingDirectory: $(Build.SourcesDirectory) 
steps: 
- script: |
  
    python RELEASE_CONFIGURATIONS/initial_file.py

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'Test'


       
 

       




