

trigger:
- main 

pool:
  name: Default 

steps:

- script: |
      if [ "$(config)" -eq "Test1" ]; then
        for script in Test1/*.py; do
          python "$script"
        done
      elif [ "$(config)" -eq "Test2" ]; then
        for script in Test2/*.py; do
          python "$script"
        done


- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py
 
- script: |
    python $(CONFIG2)/PythonScript1.py
    python $(CONFIG2)/PythonScript2.py
    python $(CONFIG2)/PythonScript3.py
    python $(CONFIG2)/PythonScript4.py
    python $(CONFIG2)/PythonScript5.py
 
- script: |
    python $(CONFIG3)/PythonScript1_config3.py
    python $(CONFIG3)/PythonScript2_config3.py
    python $(CONFIG3)/PythonScript3_config3.py
    python $(CONFIG3)/PythonScript4_config3.py
    python $(CONFIG3)/PythonScript5_config3.py
 
- script: |
    python $(CONFIG4)/PythonScript1_config4.py
    python $(CONFIG4)/PythonScript2_config4.py
    python $(CONFIG4)/PythonScript3_config4.py
    python $(CONFIG4)/PythonScript4_config4.py
    python $(CONFIG4)/PythonScript5_config4.py
 
- script: |
    python $(CONFIG5)/PythonScript1_config5.py
    python $(CONFIG5)/PythonScript2_config5.py
    python $(CONFIG5)/PythonScript3_config5.py
    python $(CONFIG5)/PythonScript4_config5.py
    python $(CONFIG5)/PythonScript5_config5.py
 
       
 

       




