

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
      RELEASE_CONFIGURATIONS/Config_1/
      RELEASE_CONFIGURATIONS/Config_2/
      RELEASE_CONFIGURATIONS/Config_3/
      RELEASE_CONFIGURATIONS/Config_4/
      RELEASE_CONFIGURATIONS/Config_5/

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- script: |

    i=PythonScript1_config1.py
    while [ $i -le PythonScript5 ]; do  # Change 5 to the number of scripts you want to execute
      echo "Executing PythonScript_$i.py"
      python RELEASE_CONFIGURATIONS/Config_$i/PythonScript_$i.py
      i=$((i+1))
    done



- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py