

trigger:
- main  # Define the branch to trigger the pipeline on, e.g., 'main' or 'master'

pool:
  name: Default  # Define the VM image to use for the build environment

steps:

- script: |
    python --version
  displayName: 'Check Python Version'




- script: |
    def main():
    print("1.1 Initializing config1...")

    if __name__ == "__main__":
    main()
