

trigger:
- main 

pool:
  name: Default 
  workingDirectory: $(Build.SourcesDirectory)/my-working-directory      
steps: 
- script: |
  
    python RELEASE_CONFIGURATIONS/initial_file.py


 
       
 

       




