

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
     Config1
     Config2
     Config3
     Config4
     Config5

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- script: |
      if [ "$(config1)" == "RELEASE_CONFIGURATIONS/Config_1" ]; then
        python PythonScript1.py
        python PythonScript2.py
        python PythonScript3.py
        python PythonScript4.py
        python PythonScript5.py
       




