

trigger:
- main 

pool:
  name: Default       
steps: 
- script: |
    python $(CONFIG1)/PythonScript1_config1.py
    python $(CONFIG1)/PythonScript2_config1.py
    python $(CONFIG1)/PythonScript3_config1.py
    python $(CONFIG1)/PythonScript4_config1.py
    python $(CONFIG1)/PythonScript5_config1.py
 
- script: |
    python $(CONFIG2)/PythonScript1_config2.py
    python $(CONFIG2)/PythonScript2_config2.py
    python $(CONFIG2)/PythonScript3_config2.py
    python $(CONFIG2)/PythonScript4_config2.py
    python $(CONFIG2)/PythonScript5_config2.py
 
- script: |
    python $(CONFIG3)/PythonScript1_config3.py
    python $(CONFIG3)/PythonScript2_config3.py
    python $(CONFIG3)/PythonScript3_config3.py
    python $(CONFIG3)/PythonScript4_config3.py
    python $(CONFIG3)/PythonScript5_config3.py
 
- script: |
    python $(CONFIG4)/PythonScript1_config4.py
    python $(CONFIG4)/PythonScript2_config4.py
    python $(CONFIG4)/PythonScript3_config4.py
    python $(CONFIG4)/PythonScript4_config4.py
    python $(CONFIG4)/PythonScript5_config4.py
 
- script: |
    python $(CONFIG5)/PythonScript1_config5.py
    python $(CONFIG5)/PythonScript2_config5.py
    python $(CONFIG5)/PythonScript3_config5.py
    python $(CONFIG5)/PythonScript4_config5.py
    python $(CONFIG5)/PythonScript5_config5.py

- script: |
    workingDirectory: $(Build.SourcesDirectory)
    python run_script.py Config_1 Config_2 Config_3 Config_4 Config_5
    python RELEASE_CONFIGURATIONS/initial_file.py


 
       
 

       




