

trigger:
- main 

pool:
  name: Default 

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- script: |
  displayName: Test1
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py

- script: |
  displayName: Test2
    python $(CONFIG2)/PythonScript1_config2.py
    python $(CONFIG2)/PythonScript2_config2.py
    python $(CONFIG2)/PythonScript3_config2.py
    python $(CONFIG2)/PythonScript4_config2.py
    python $(CONFIG2)/PythonScript5_config2.py

- script: |
  displayName: Test3
    python $(CONFIG3)/PythonScript1_config3.py
    python $(CONFIG3)/PythonScript2_config3.py
    python $(CONFIG3)/PythonScript3_config3.py
    python $(CONFIG3)/PythonScript4_config3.py
    python $(CONFIG3)/PythonScript5_config3.py

- script: |
  displayName: Test4
    python $(CONFIG4)/PythonScript1_config4.py
    python $(CONFIG4)/PythonScript2_config4.py
    python $(CONFIG4)/PythonScript3_config4.py
    python $(CONFIG4)/PythonScript4_config4.py
    python $(CONFIG4)/PythonScript5_config4.py

- script: |
  displayName: Test5
    python $(CONFIG5)/PythonScript1_config5.py
    python $(CONFIG5)/PythonScript2_config5.py
    python $(CONFIG5)/PythonScript3_config5.py
    python $(CONFIG5)/PythonScript4_config5.py
    python $(CONFIG5)/PythonScript5_config5.py
       




