

trigger:
- main 

pool:
  name: Default 

variables:
  - name: Config
    value: |
     Config1
     Config2
     Config3
     Config4
     Config5

steps:
- script: |
    python --version
  displayName: 'Check Python Version'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      for config_value in config1 config2 config3 config4 config5; do
              if [ "$(config)" == "$config_value" ]; then
                python "python${config_value: -1}.py"
                break
              fi
            done




- script: |
    python $(CONFIG1)/PythonScript1.py
    python $(CONFIG1)/PythonScript2.py
    python $(CONFIG1)/PythonScript3.py
    python $(CONFIG1)/PythonScript4.py
    python $(CONFIG1)/PythonScript5.py