

trigger:
- main 

pool:
  name: Default 

steps:
- checkout: self
  path: ./Config_1 # Checkout config1 directory from the repository

- script: |

    python ./PythonScript1.py
    python ./PythonScript2.py
    python ./PythonScript3.py
    python ./PythonScript4.py
    python ./PythonScript5.py




       




