

trigger:
- main  # Define the branch to trigger the pipeline on, e.g., 'main' or 'master'

pool:
  name: Default  # Define the VM image to use for the build environment

steps:

- script: |
    python --version
  displayName: 'Check Python Version'




- script: |
    python RELEASE_CONFIGURATIONS/Config_1/PythonScript2_config1.py
